### ISSUE TITLE
problem with reverse() in deleteUrl

### ISSUE THREAD

**Issue by dovivi** [sigurdga/django-jquery-file-upload#73]
I get a NoReverseMatch error coming from the deleteUrl method on `serielize.py`. When I have uploaded a file and refresh the page then I get the following:

```
[11/May/2018 10:50:32] "GET /upload/new/ HTTP/1.1" 200 12321
[11/May/2018 10:50:32] "GET /static/css/style.css HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/css/jquery.fileupload-ui.css HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/css/blueimp-gallery.min.css HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/vendor/jquery.ui.widget.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/tmpl.min.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/load-image.min.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/bootstrap.min.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/canvas-to-blob.min.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/jquery.blueimp-gallery.min.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/jquery.iframe-transport.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/jquery.fileupload-process.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/jquery.fileupload.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/jquery.fileupload-image.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/jquery.fileupload-audio.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/jquery.fileupload-video.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/jquery.fileupload-validate.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/jquery.fileupload-ui.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/main.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/locale.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/js/csrf.js HTTP/1.1" 304 0
[11/May/2018 10:50:32] "GET /static/img/loading.gif HTTP/1.1" 304 0
Internal Server Error: /upload/view/
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/exception.py", line 41, in inner
    response = get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/local/lib/python2.7/dist-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/django/views/generic/list.py", line 176, in get
    return self.render_to_response(context)
  File "/home/mvidal/Downloads/django-jquery-file-upload-master/fileupload/views.py", line 58, in render_to_response
    files = [ serialize(p) for p in self.get_queryset() ]
  File "/home/mvidal/Downloads/django-jquery-file-upload-master/fileupload/serialize.py", line 34, in serialize
    'deleteUrl': reverse('upload-delete', args=[instance.pk]),
  File "/usr/local/lib/python2.7/dist-packages/django/urls/base.py", line 91, in reverse
    return force_text(iri_to_uri(resolver._reverse_with_prefix(view, prefix, *args, **kwargs)))
  File "/usr/local/lib/python2.7/dist-packages/django/urls/resolvers.py", line 497, in _reverse_with_prefix
    raise NoReverseMatch(msg)
NoReverseMatch: Reverse for 'upload-delete' with arguments '(1,)' not found. 1 pattern(s) tried: ['upload/delete/<int:pk>']
[11/May/2018 10:50:33] "GET /upload/view/ HTTP/1.1" 500 19065
```

I am running the app without major changes, the only modifications I did were the following:
- instead of using `path` for the urls, I use `url` because I am using Django 1.11
- I removed `path('', lambda x: HttpResponseRedirect('/upload/new/'))` from root urls because even I changed to `url('', lambda x: HttpResponseRedirect('/upload/new/'))` it was not working 

I wonder if it's not working because I am using Django 1.11 or maybe because I changed `path` for `url` or why..?

Thanks

**Comment by dovivi** [comment]
Well, after some search I changed how the url for 'upload-delete' is set:
instead of `url('delete/<int:pk>', PictureDeleteView.as_view(), name='upload-delete'),` I use
   `url('delete/(?P<pk>[0-9]+)$', PictureDeleteView.as_view(), name='upload-delete'),` in `urls.py` of  `fileupload` app.
Now everything works.
